### ISSUE TITLE
SWE-bench-lite failing instances inconsistent with logs

### ISSUE THREAD

**Issue by dvendrow** [aorwall/SWE-bench-docker#11]
The [SWE-bench_Lite_golden](https://github.com/aorwall/SWE-bench-docker/tree/main/evaluations/SWE-bench_Lite_golden) report states that only 2 tasks, pydata__xarray-4094 and pydata__xarray-4493, are failing evaluation. However, in the [logs](https://github.com/aorwall/SWE-bench-docker/tree/main/evaluations/SWE-bench_Lite_golden/logs) provided, the following 44 tasks appear to be failing evaluation:

astropy__astropy-6938
django__django-15400
matplotlib__matplotlib-22711
matplotlib__matplotlib-23299
matplotlib__matplotlib-24970
matplotlib__matplotlib-25079
matplotlib__matplotlib-25311
matplotlib__matplotlib-25332
mwaskom__seaborn-2848
pallets__flask-4045
psf__requests-1963
psf__requests-2148
psf__requests-2317
psf__requests-2674
psf__requests-3362
psf__requests-863
pydata__xarray-4094
pydata__xarray-4493
pylint-dev__pylint-7080
pylint-dev__pylint-7114
pytest-dev__pytest-5103
pytest-dev__pytest-5495
sphinx-doc__sphinx-7686
sphinx-doc__sphinx-8474
sphinx-doc__sphinx-8506
sphinx-doc__sphinx-8713
sphinx-doc__sphinx-8721
sympy__sympy-11897
sympy__sympy-12236
sympy__sympy-12454
sympy__sympy-13043
sympy__sympy-13146
sympy__sympy-13647
sympy__sympy-13773
sympy__sympy-13915
sympy__sympy-13971
sympy__sympy-14308
sympy__sympy-14817
sympy__sympy-15308
sympy__sympy-15609
sympy__sympy-16106
sympy__sympy-16281
sympy__sympy-16503
sympy__sympy-18199

**Comment by aorwall** [comment]
Which evaluation report script are you using? I generated the report with the [get_model_report](https://github.com/princeton-nlp/SWE-bench/blob/main/swebench/metrics/report.py#L271) function from swebench. My guess is that the failing tests aren't listed in `FAIL_TO_PASS` or `PASS_TO_PASS`?

It's not super clear which tests we expect to fail though as I haven't found any golden patch logs from the original SWE-Bench setup. The logs from the SWE-Agent benchmarks could give some hints on if we expect the tests to fail or not https://github.com/swe-bench/experiments/tree/main/evaluation/lite/20240402_sweagent_gpt4/logs

**Comment by dvendrow** [comment]
Got it, thanks! I was simply checking for ">>>>> All Tests Passed".
