### ISSUE TITLE
Unable to reproduce evaluation for 10 SWE-bench-lite instances

### ISSUE THREAD

**Issue by dvendrow** [aorwall/SWE-bench-docker#12]
Thank you for your quick responses.

I am unable to reproduce evaluation results for the following 10 SWE-bench-lite instances using the golden predictions provided in the repo. Here are my logs:

[matplotlib__matplotlib-25311.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407622/matplotlib__matplotlib-25311.SWE-bench_Lite_golden.eval.log)
[matplotlib__matplotlib-25332.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407623/matplotlib__matplotlib-25332.SWE-bench_Lite_golden.eval.log)
[matplotlib__matplotlib-25433.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407624/matplotlib__matplotlib-25433.SWE-bench_Lite_golden.eval.log)
[matplotlib__matplotlib-25442.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407625/matplotlib__matplotlib-25442.SWE-bench_Lite_golden.eval.log)
[matplotlib__matplotlib-25498.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407626/matplotlib__matplotlib-25498.SWE-bench_Lite_golden.eval.log)
[pylint-dev__pylint-7080.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407627/pylint-dev__pylint-7080.SWE-bench_Lite_golden.eval.log)
[pytest-dev__pytest-7168.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407637/pytest-dev__pytest-7168.SWE-bench_Lite_golden.eval.log)
[pytest-dev__pytest-7220.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407638/pytest-dev__pytest-7220.SWE-bench_Lite_golden.eval.log)
[sympy__sympy-13146.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407640/sympy__sympy-13146.SWE-bench_Lite_golden.eval.log)
[sympy__sympy-13177.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15407641/sympy__sympy-13177.SWE-bench_Lite_golden.eval.log)

For example, here is the my eval log for matplotlib__matplotlib-25311. The rest of the failing matplotlib__matplotlib instances look similar to this:
```
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Task Metadata:
	- Instance ID: matplotlib__matplotlib-25311
	- Testbed: matplotlib__matplotlib__3.7
	- 
	- Evaluation Model: SWE-bench_Lite_golden 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git status --porcelain 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": true, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git -c advice.detachedHead=false checkout 430fb1db88843300fb4baae3edc499bbfe073b0c 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": true, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
Previous HEAD position was 0849036fd9 Merge pull request #26201 from melissawm/add-codespaces-docs
HEAD is now at 430fb1db88 Merge pull request #25320 from larrybradley/fix-typo
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git apply -v /home/swe-bench/temp_matplotlib__matplotlib-25311_pred_try.patch 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": false, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
Checking patch lib/matplotlib/offsetbox.py...
Applied patch lib/matplotlib/offsetbox.py cleanly.
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Apply patch successful (pred_try) 
>>>>> Applied Patch (pred_try)
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git apply -v -R /home/swe-bench/temp_matplotlib__matplotlib-25311_pred_try.patch 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": false, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
Checking patch lib/matplotlib/offsetbox.py...
Applied patch lib/matplotlib/offsetbox.py cleanly.
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Revert patch successful (pred_try) 
>>>>> Applied Patch (pred_try)
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git apply -v /home/swe-bench/temp_matplotlib__matplotlib-25311_pred.patch 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": false, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
Checking patch lib/matplotlib/offsetbox.py...
Applied patch lib/matplotlib/offsetbox.py cleanly.
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Apply patch successful (pred) 
>>>>> Applied Patch (pred)
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git restore lib/matplotlib/tests/test_pickle.py 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": true, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: git apply -v /home/swe-bench/temp_matplotlib__matplotlib-25311_test.patch 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": false, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
Checking patch lib/matplotlib/tests/test_pickle.py...
Applied patch lib/matplotlib/tests/test_pickle.py cleanly.
 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 0 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Apply patch successful (test) 
>>>>> Applied Patch (test)
Test Script: conda run -n matplotlib__matplotlib__3.7 pytest --no-header -rA --tb=no -p no:cacheprovider lib/matplotlib/tests/test_pickle.py;
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Command: conda run -n matplotlib__matplotlib__3.7 pytest --no-header -rA --tb=no -p no:cacheprovider lib/matplotlib/tests/test_pickle.py 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Subprocess args: {"cwd": "/home/swe-bench/matplotlib__matplotlib", "check": false, "shell": false, "capture_output": false, "text": true, "stdout": -1, "stderr": -2, "timeout": 1800} 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Std. Output:
ERROR conda.cli.main_run:execute(124): `conda run pytest --no-header -rA --tb=no -p no:cacheprovider lib/matplotlib/tests/test_pickle.py` failed. (See above for error)
============================= test session starts ==============================
collected 0 items / 1 error

=========================== short test summary info ============================
ERROR lib/matplotlib/tests/test_pickle.py - DeprecationWarning: pkg_resources...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.90s ===============================

 
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Return Code: 2 

>>>>> Some Tests Failed
[matplotlib__matplotlib__3.7] [matplotlib__matplotlib-25311] Test script run successful 
```

Here is a quick summary of the failures for the other repos:
pylint-dev__pylint-7080: failing a couple more tests than the reference log
pytest-dev__pytest-7168: `ImportError: cannot import name 'console_main' from 'pytest' (/home/swe-bench/pytest-dev__pytest/src/pytest/__init__.py)`
pytest-dev__pytest-7220: `ModuleNotFoundError: No module named 'wcwidth'`
sympy__sympy-13146: failing a couple more tests than the reference log
sympy__sympy-13177: failing a couple more tests than the reference log

**Comment by dvendrow** [comment]
Update: I was able to resolve the matplotlib__matplotlib errors by adding `-W ignore::DeprecationWarning` to the pytest command.

The only matplotlib__matplotlib instance still failing is matplotlib__matplotlib-25433, now for a different reason:
`SKIPPED [1] lib/matplotlib/tests/test_backend_bases.py:283: xelatex + pgf is required`

[matplotlib__matplotlib-25433.SWE-bench_Lite_golden.eval.log](https://github.com/aorwall/SWE-bench-docker/files/15409881/matplotlib__matplotlib-25433.SWE-bench_Lite_golden.eval.log)

**Comment by aorwall** [comment]
I get the same issue on sympy__sympy-13146 now, but I wonder if that test is flaky, seems to work sometimes. But the other works with my build and pushed docker images.

Did you build the docker images or used the ones from docker hub?

**Comment by dvendrow** [comment]
> I get the same issue on sympy__sympy-13146 now, but I wonder if that test is flaky, seems to work sometimes. But the other works with my build and pushed docker images.
> 
> Did you build the docker images or used the ones from docker hub?

Thanks for checking. I am using the images from docker hub and these tasks are failing consistently for me.

**Comment by aorwall** [comment]
Can you try to pull the images again now to see if the rebuilt ones works better?

**Comment by dvendrow** [comment]
I re-pulled the images. pylint-dev__pylint-7080, pytest-dev__pytest-7168, and pytest-dev__pytest-7220 are passing now. 

I am still seeing the `ERROR lib/matplotlib/tests/test_pickle.py - DeprecationWarning: pkg_resources...` issue for the 5 matplotlib tasks which I can fix with the pytest command addition.

The only remaining tasks which don't reproduce after that are these two, with the same reason as before:

matplotlib__matplotlib-25433
- `SKIPPED [1] lib/matplotlib/tests/test_backend_bases.py:283: xelatex + pgf is required`

sympy__sympy-13177
- failing more tests

**Comment by dvendrow** [comment]
When I build the docker images myself, I get all passing except for these 3:

pydata__xarray-4094
pydata__xarray-4493
sympy__sympy-13146

So it's possibly something machine specific. Closing for now.
