### ISSUE TITLE
SWE-bench Docker images

### ISSUE THREAD

**Issue by dvendrow** [aorwall/SWE-bench-docker#13]
I noticed that the images for the full SWE-bench set (i.e. the ones used for the SWE-bench_check_harness evaluation) are not on Docker Hub. Do you also plan on pushing those? Thanks!

**Comment by aorwall** [comment]
Not right now, because of the amount of work that would be needed. Many of the instances in the harness dataset are still failing, which makes me suspect that it will be hard to make the current testbeds work for all ~2300 instances.
