### ISSUE TITLE
Building pydata and matplotlib fail with ERROR: failed to solve: aorwall/swe-bench-conda:bookworm-slim

### ISSUE THREAD

**Issue by paul-gauthier** [aorwall/SWE-bench-docker#14]
I was able to build docker images for most of SWE Bench. But these commands:

```
./scripts/build_docker_images.sh docker aorwall pydata__xarray
./scripts/build_docker_images.sh docker aorwall matplotlib__matplotlib
```

Fail like this:

```
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 499B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/aorwall/swe-bench-conda:bookworm-slim
#3 ...

#4 [auth] aorwall/swe-bench-conda:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/aorwall/swe-bench-conda:bookworm-slim
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/aorwall/swe-bench-conda:bookworm-slim:
------
Dockerfile:3
--------------------
   1 |     # Generated by generate_dockerfiles.py
   2 |
   3 | >>> FROM aorwall/swe-bench-conda:bookworm-slim
   4 |
   5 |
--------------------
ERROR: failed to solve: aorwall/swe-bench-conda:bookworm-slim: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Any suggestions?

**Comment by aorwall** [comment]
Seems like it wasn't pushed. I've rebuilt and pushed all images except for astropy/astropy which for some reason doesn't build now. I created a Makefile that might be more reliable than the build_docker_images.sh script now also. 

I do get two new failing benchmark instances now though, see the [report](https://github.com/aorwall/SWE-bench-docker/blob/main/evaluations/SWE-bench_Lite_golden/README.md). My guess is that [sympy__sympy-13146](https://github.com/aorwall/SWE-bench-docker/blob/main/evaluations/SWE-bench_Lite_golden/logs/sympy__sympy-13146.SWE-bench_Lite_golden.eval.log) is a flaky test that sometimes succeeds though. Can you check if you get the same failing tests?

**Comment by paul-gauthier** [comment]
Thanks for the quick reply. The reason I was trying to rebuild those images is because when I run tests on these instances I get the following docker errors:

- matplotlib__matplotlib-20470
- matplotlib__matplotlib-20761
- matplotlib__matplotlib-21550

```
2024-05-27 06:00:51,200 - swebench_docker.run_docker - WARNING - Stdout - Unable to find image 'aorwall/swe-bench-matplotlib_matplotlib-testbed:3.4' locally
docker: Error response from daemon: manifest for aorwall/swe-bench-matplotlib_matplotlib-testbed:3.4 not found: manifest unknown: manifest unknown.
```

- pydata__xarray-5365

```
2024-05-27 06:01:42,090 - swebench_docker.run_docker - WARNING - Stdout - Unable to find image 'aorwall/swe-bench-pydata_xarray-testbed:0.18' locally
docker: Error response from daemon: manifest for aorwall/swe-bench-pydata_xarray-testbed:0.18 not found: manifest unknown: manifest unknown.
```

- pydata__xarray-6400

```
2024-05-27 06:03:16,474 - swebench_docker.run_docker - WARNING - Stdout - Unable to find image 'aorwall/swe-bench-pydata_xarray-testbed:2022.03' locally
docker: Error response from daemon: manifest for aorwall/swe-bench-pydata_xarray-testbed:2022.03 not found: manifest unknown: manifest unknown.
```

- pydata__xarray-7150
- pydata__xarray-7391
- pydata__xarray-7393

```
2024-05-27 06:04:29,775 - swebench_docker.run_docker - WARNING - Stdout - Unable to find image 'aorwall/swe-bench-pydata_xarray-testbed:2022.09' locally
docker: Error response from daemon: manifest for aorwall/swe-bench-pydata_xarray-testbed:2022.09 not found: manifest unknown: manifest unknown.
```

I can't seem to `docker pull` any of those images. And when I look in the `Makefile` on the latest pull from your repo, I don't see any indication that it would build those images.

But maybe I am missing something?

To be clear, these are instances from the full SWE Bench dataset, not Lite.

**Comment by aorwall** [comment]
Aha, I never pushed the generated Dockerfiles or the docker images for SWE-Bench images as many are still failing. The error you got should be solved now. But the build might fail for other reasons anyway then...

**Comment by paul-gauthier** [comment]
Yes, I was able to build them after running these lines from your new Makefile.

```
	docker build -t aorwall/swe-bench-conda:bookworm-slim -f "docker/Dockerfile .
	docker build -t aorwall/swe-bench-pyenv:bookworm-slim -f "docker/pyenv/Dockerfile .
	docker build -t aorwall/swe-bench-pyenvs:bookworm-slim -f "docker/pyenv/Dockerfile-pyenvs .
```

Two things I wanted to bring to your attention though:

1. There seem to be stray quotes in those lines, which I had to remove.
2. When I used `run_dockerfile_generator.py` to generate against the full SWE Bench, it rebuilt the Makefile without those lines.

Thanks again!

**Comment by aorwall** [comment]
Thanks. I added them to the `run_dockerfile_generator.py`
