### ISSUE TITLE
Argument to run arbitrary tests on prediction/instance?

### ISSUE THREAD

**Issue by granawkins** [aorwall/SWE-bench-docker#16]
We ([AbanteAI](https://www.mentat.ai/)) are using swe-bench quite a lot in developing and benchmarking our coding agent, and are adding this docker image to our workflow - thanks for building it!

We give our agents the ability to select and run arbitary tests from the repo as part of its development process (before swe-bench evaluation). It'd be convenient to use this Docker environment, since it's already setup for the specific codebase/instance.

Would you consider supporting this? If you like I could put together a PR. Thanks.

**Comment by aorwall** [comment]
I've been thinking of the same use case. So it would be greatly appreciated.
