### ISSUE TITLE
The Gold Patch for `psf__requests-863' fails.

### ISSUE THREAD

**Issue by t-kurabayashi** [aorwall/SWE-bench-docker#22]
The Gold Patch for `psf__requests-863` is failing.
[psf__requests-863.log](https://github.com/user-attachments/files/15594082/psf__requests-863.log) is my logs:

This log is clearly different from the correct [log](https://github.com/aorwall/SWE-bench-docker/blob/main/evaluations/SWE-bench_Lite_golden/logs/psf__requests-863.SWE-bench_Lite_golden.eval.log).

I generated the report with the get_model_report function from swebench.
However, it was judged as a failure.

I also tried the following command, but the result was the same.
```
scripts/build_single_docker_image.sh aorwall docker/psf__requests/0.14
python run_instance_tests.py --instance_id psf__requests-863
```

**Comment by aorwall** [comment]
Seems like the intermittent issues in psf/requests tests is because the tests does requests to  httpbin.org which sometimes fails. I stabilised these tests in the hosted environment (https://eval.moatless.ai) by using a self hosted httpbin.
