### ISSUE TITLE
"None/swebench_docker" includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by voidking** [aorwall/SWE-bench-docker#27]
```bash
python /data/SWE-bench-docker/run_evaluation.py --predictions_path /path/to/xxx.jsonl --log_dir  /tmp/swe-bench/ --swe_bench_tasks princeton-nlp/SWE-bench_Lite
```
Error log:
2024-06-12 19:56:38,251 - swebench_docker.run_docker - WARNING - Stdout - docker: Error response from daemon: create None/swebench_docker: "None/swebench_docker" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**Comment by voidking** [comment]
From code [run_docker.py](https://github.com/aorwall/SWE-bench-docker/blob/main/swebench_docker/run_docker.py), we can see that if `SWEBENCH_DOCKER_FORK_DIR` does not exist then the error will accur.

**Comment by voidking** [comment]
After I have specified a environment variable `SWEBENCH_DOCKER_FORK_DIR`, the error disappear.
However, another error accur: 
```text
2024-06-12 20:12:13,314 - swebench_docker.run_docker - WARNING - Command: docker run --rm -v /tmp/lite-3/:/opt/logs -v /data/haojin/SWE-bench-docker/swebench_docker:/opt/swebench_docker:ro -v /data/SWE-bench-docker/swebench_docker:/home/swe-bench/swebench_docker:ro -v /data/SWE-bench-docker/swebench_docker:/home/swe-bench/swebench:ro -v /tmp/tmp40_3vdlf.json:/home/swe-bench/task_instance.json:ro -e LOG_DIR=/opt/logs -e TIMEOUT=1800 -e LOG_SUFFIX= aorwall/swe-bench-sympy_sympy-testbed:1.5
2024-06-12 20:12:13,314 - swebench_docker.run_docker - WARNING - Stdout - Starting evaluate_instance.py...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 78, in <module>
    with open(TASK_INSTANCE_JSON, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/swe-bench/task_instance.json'
```
This error maybe due to `with tempfile.NamedTemporaryFile(delete=False, mode='w+', suffix='.json') as tmpfile`.   
It is expected to creates a temporary file, but in fact it creates a directory. 
I think the executing order may have some problem. The `docker run` creates a directory rather than the `tempfile.NamedTemporaryFile` creates a file.  
![image](https://github.com/aorwall/SWE-bench-docker/assets/9190516/02398b05-0fd7-4ee6-b28c-24e802843a41)

**Comment by aorwall** [comment]
@xingyaoww could this be related to your changes?

**Comment by voidking** [comment]
```bash
docker run --rm -v /tmp/lite-3/:/opt/logs -v /data/haojin/SWE-bench-docker/swebench_docker:/opt/swebench_docker:ro -v /data/haojin/SWE-bench-docker/swebench_docker:/home/swe-bench/swebench_docker:ro -v /data/haojin/SWE-bench-docker/swebench_docker:/home/swe-bench/swebench:ro -v /tmp/tmpwogmy5hx.json:/home/swe-bench/task_instance.json:ro -e LOG_DIR=/opt/logs -e TIMEOUT=1800 -e LOG_SUFFIX= aorwall/swe-bench-astropy_astropy-testbed:1.3
```
Error stdout: fatal: detected dubious ownership in repository at '/home/swe-bench/astropy__astropy'
![image](https://github.com/aorwall/SWE-bench-docker/assets/9190516/8b151981-4381-499f-85ea-17e7cb936a57)

**Comment by xingyaoww** [comment]
Thanks for the fix!! Yes, for some reason i forget to update the documentation highlight the need for a fork of `SWEBENCH_DOCKER_FORK_DIR` due to updated code :(

But i think the https://github.com/voidking/SWE-bench-docker/commit/35c20cf8a205e4b905ae9a427c702eefba2ebb8b should fix this issue.

> I think the executing order may have some problem. The docker run creates a directory rather than the tempfile.NamedTemporaryFile creates a file.

agh i didn't run into this :(
Maybe the bug is due to different docker setup.  I'm currently traveling so hard to find time to take a look, but can help take a look over the weekend.

For file permission, I remember someone from OpenDevin slack channel tries to set permission of the file to `666` and then resolve the problem -- not sure if it helps here.
Context: https://opendevin.slack.com/archives/C06U7J3D2CT/p1718194779720809?thread_ts=1718121544.775639&cid=C06U7J3D2CT

**Comment by voidking** [comment]
@xingyaoww Thank you for providing other ideas. You can take a look at my implementation to see if there are any problems or if there are any shortcomings. Then we can make it better.  
The git error was caused by git safe control. If we create docker image with user A and run image with user B, an error will reported: fatal: detected dubious ownership in repository at xxx
As far as I know, the image was created by root, ubuntu, swe-bench, etc. My solution is run all images by user root and exec `git config --global --add safe.directory xxx` first.

**Comment by aorwall** [comment]
I readded the base64 solution and made it possible to opt in to the new solution to not break the workflow for other folks (and me :sweat_smile: ). Even if the base64 solution is ugly it's convenient....

**Comment by voidking** [comment]
> I readded the base64 solution and made it possible to opt in to the new solution to not break the workflow for other folks (and me 😅 ). Even if the base64 solution is ugly it's convenient....

Haha, any method that can solve the problem is a good method.
