### ISSUE TITLE
Unpinned SWE-bench version

### ISSUE THREAD

**Issue by prabhuteja12** [aorwall/SWE-bench-docker#35]
Pip installing the requirements installs a version of SWE-bench that seems to cause some issues. Specifically, running `python run_evaluation.py .....` results in 

```
ImportError: cannot import name 'get_eval_refs' from 'swebench'
```
at the import of on line number 10.
I'm unable to find this function in SWE-bench mainline as well. Can you please help me with this?

Thanks!

**Comment by aorwall** [comment]
It might be possible to solve by pinning the swebench dependency to <2.0. But this tool isn't maintained any longer as the SWE-bench team's own containerized solution is more stable. My suggestion is to use that one or try my hosted version at https://eval.moatless.ai.

**Comment by prabhuteja12** [comment]
ok. thank you!
