### ISSUE TITLE
Unable to find image aorwall/swe-bench-scikit-learn...

### ISSUE THREAD

**Issue by paul-gauthier** [aorwall/SWE-bench-docker#6]
Thank you for dockerizing this! I've been able to run evaluations for far more of the SWE Bench Lite instances with your setup compared to the original repo's conda harness.

I did notice that the `run_evaluation.py` script is not able to pull the `scikit-learn` image, see below.

```
2024-05-10 14:25:41,606 - swebench_docker.run_docker - WARNING - Stdout - Unable to find image 'aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-10508' locally
docker: Error response from daemon: pull access denied for aorwall/swe-bench-scikit-learn_scikit-learn-instance, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

I see that you've provided a way for me to rebuild all the docker images myself. But given that most of your images seem to be available, I figured I would check if you left out scikit by mistake?

**Comment by aorwall** [comment]
I had to build an image for each `scikit-learn` instance and might have missed to push them. I'm doing it right now but might take a while. So you can try to build them with `./scripts/build_docker_images.sh docker aorwall scikit-learn__scikit-learn`

**Comment by paul-gauthier** [comment]
Thanks! That build command solved this for me. 

Again, I really appreciate the work dockerizing these testbeds. I hope the upstream adopts this approach.
